---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/image1/default_figure.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/170837/articles/289348/master/file/figures/image1/default_figure.png"
    folder_url: "/users/170837/articles/289348/master/folder/figures/image1"
