---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/The_Great_Wave_off_Kanagawa/The_Great_Wave_off_Kanagawa.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/170837/articles/289348/master/file/figures/The_Great_Wave_off_Kanagawa/The_Great_Wave_off_Kanagawa.png"
